apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  image: test-env-kafka-connect:strimzi-3.0
  groupId: connect-cluster
  offsetStorageTopic: connect-cluster-offsets
  configStorageTopic: connect-cluster-configs
  statusStorageTopic: connect-cluster-status
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: xml-sink-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: xml.converter.XmlConverterSinkConnector
  tasksMax: 1
  config:
    topics: avro-source
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry:8081
    xml.target.topic: xml-target
    xml.root.element.name: testRecord
    xml.producer.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    xml.producer.acks: all
